version: '3.8'

services:
  
  mongo:
    image: mongo:6.0
    container_name: hackathon-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db 
    networks:
      - hackathon-net
    
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: hackathon-backend
    environment:
      - PORT=3847
      - BACKEND_PORT=3847
      - SERVER_PORT=3847
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - hackathon-net
    
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: hackathon-gateway
    ports:
      - "5921:8080" 
    environment:
      - PORT=${GATEWAY_PORT}
      - BACKEND_URL=http://backend:${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - hackathon-net


networks:
  hackathon-net:
    driver: bridge


volumes:
  mongo-data: